intern/resource/boss/resource.py
intern/resource/boss/tests/test_experiment.py

The management console allows creation of experiments w/o specifying the
time step.  The REST API will return a blank string for the time step
unit in this case.
Addresses https://github.com/jhuapl-boss/intern/issues/7

Allow unspecified time step unit for experiments.

---

intern/remote/boss/tests/int_test_project_v1.py
intern/resource/boss/resource.py
intern/resource/boss/tests/test_channel.py
intern/service/boss/volume.py

This is a more appropriate name for the ChannelResource's property as discussed in https://github.com/jhuapl-boss/intern/pull/4

Renamed fully_initialized to cutout_ready.

---

intern/service/boss/v1/volume.py

This closes #6. Will return cutout in the correct datatype based on the channel_resource.

explicitly set datatype for cutouts

---

docs/remote/boss/remote.m.html
intern/remote/boss/remote.py
intern/remote/remote.py
intern/service/boss/baseversion.py
intern/service/boss/v1/volume.py
intern/service/boss/volume.py

Adds the option to get_cutout without using cache. 
Defaults to no_cache = False. 
Use:
```python
boss = BossRemote()
volume = boss.get_cutout(
boss.get_channel("chan", "coll", "expp"), 1,
[10000, 10500], [10000, 10500], [500, 550], no_cache = True,
)
```

No-cache get_cutout() feature

---

intern/service/boss/baseversion.py

Fixes no_cache bug by removing appended `/` when defining request param. 
It seems the extra `/` leads to the boss comparing `true/` to `true`, and thus does not correctly request `no-cache=True`

Fixes no_cache bug

---

intern/service/boss/v1/volume.py

I believe this will resolve the no_cache issue. The test code we used before used chunk sizes that were below the threshold that would activate this logic. The chunk sizes I am using in production (2048x2048x32) are 2x the threshold of activating the recursive logic (1024x1024x32x2).

fix: add no_cache to recursive get_cutout call

---

intern/service/boss/v1/tests/test_volume.py

Make sure any call to get_cutout() uses no_cache = True by default.
Add unit tests to catch potential breaking changes to the no_cache flag.

Ensure no_cache flag defaults to True.

---

intern/remote/boss/remote.py

Convenience capabilities

---

CHANGELOG.md
intern/service/boss/v1/tests/test_volume.py
intern/service/boss/v1/volume.py

On large chunks of data passed to create_cutout, chunk the data into smaller components to post individually (to avoid HTTP timeout or size limitation).

Add chunking procedure to create_cutout

---

intern/remote/boss/remote.py
intern/service/boss/v1/volume.py
intern/service/boss/volume.py

Simple function to get the neuroglancer url link of a channel given the same parameters as the `get_cutout` function. 
Only available for the boss remote. 
Let me know if perhaps the code should be moved to another location. Thought volume service would be the most appropriate. 
Sample script:
```python
import intern
from intern.remote.boss import BossRemote
rmt = BossRemote({
"protocol": "https",
"host": "api.theboss.io",
"token": "TOKEN"
})
col = 'kasthuri2015'
exp = 'em'
chan = 'cc'
initial_res = 0
#Bounds
x_bounds = [6400,6400+100]
y_bounds = [9000,9000+100]
z_bounds = [843, 848]
#Get link
neuroLink= rmt.get_neuroglancer_link(rmt.get_channel(chan, col, exp),initial_res,x_bounds,y_bounds,z_bounds,)
print(neuroLink)
```
>Output: …

Adds get_cutout_link function

---

intern/remote/boss/remote.py
intern/remote/boss/tests/test_remote_get_cutout.py
intern/resource/boss/resource.py
intern/service/boss/baseversion.py
intern/service/boss/tests/test_baseversion.py
intern/service/boss/v1/tests/test_volume.py
intern/service/boss/v1/volume.py
intern/service/boss/volume.py

This PR updates intern to correctly make requests specifying an `access_mode` due to the changes in jhuapl-boss/spdb#9 .
Updates:
- `intern` incorporates the `access_mode` parameter when grabbing cutouts of  small AND large sizes. 
- Backwards compatibility with previous versions that make use of the `no_cache` boolean parameter. 
- Whenever a user makes use of the `no_cache` param intern will return a deprecation warning..=
-The translation occurs in intern/remote/boss/remote.py and should be removed in future major version upgrades. 
- `intern` uses the an enum class to limit the possibility of cache modes. 
An example of how to use the new `access_mode` param is below:
```python
boss = BossRemote({
"protocol": "https",
"host": "api.theboss.io",
"token": "TOKEN",
})
volume = …
```

Raw no cache mode feature

---

intern/service/boss/baseversion.py

Had to make a hotfix to the access_mode update. 
Turns out urllib is very different between python2 and python3. Online most people recommend, if you want to have something that works well for both python2 and python3 you should just create the functions yourself.
Here I eliminate our dependency on urllib and create the url myself. 
Let me know if you have any suggestions.

Hotfixes to make master python2 compatible

---

setup.py

twine now blocks uploads without long_description_content_type
Originally received this error:
_HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText_
https://github.com/pypa/warehouse/issues/5890

added long_description_content_type to setup.py

---

intern/service/boss/service.py

`intern`'s `requests` calls should respect environment variables set in the shell.

Inherit env variables from the shell session

---

CHANGELOG.md
intern/remote/boss/remote.py
intern/remote/boss/tests/test_remote_get_cutout.py
intern/remote/remote.py
intern/service/boss/v1/tests/test_volume.py
intern/service/boss/v1/volume.py

You can now pass a `parallel=True` (will use your number of cores) or `parallel=<int number of jobs>` argument to `BossRemote#get_cutout` in order to spread chunk downloads over a `multiprocessing.Pool#starmap`.
On a few informal stress-tests, this improved download speed by 37–40%.
You can still use the old behavior with `parallel=False`.

BossRemote#get_cutout parallelism

---

CHANGELOG.md
intern/convenience/array.py

Annotation channels require a `source_channel` to be specified at creation-time. This enables the convenience-API array() constructor to create annotation channels (`uint16` and `uint64` segmentation).
```python
from intern import array
array(
"bossdb://collection/experiment/segmentation",
create_new=True,
dtype="uint64",
source_channel="image" # refers to "bossdb://collection/experiment/image"
)
```
When creating an annotation channel in an existing experiment, coordinate-frame information is not required (`voxel_size`, `voxel_units`, `extents`) since the collection, experiment, and coordinate-frame will already exist.

[Convenience API] Add source_channel option for annotations

---

CHANGELOG.md
intern/__init__.py
intern/version/__init__.py
requirements.txt
setup.py

We were importing from `intern` before it was installed (to get `version` in the root of the package), which to the best of my understanding has fallen out of favor as a way of checking the package version. This is a nonbreaking, backwards-compatible change.

Fix pip-installability

---

intern/remote/boss/remote.py
intern/remote/boss/tests/int_test_volume_v1.py
intern/service/boss/baseversion.py
intern/service/boss/tests/test_baseversion.py
intern/service/boss/v1/volume.py
intern/service/boss/volume.py

Adds necessary remote functions and tests to utilize the bossDB cutout_to_black API call. With this addition, users can now upload black tiles easily without having to use ingest client.
Remote function call:
```python
BossRemote.create_cutout_to_black(resource, resolution, x_range, y_range, z_range, t_range)
```

cutout_to_black addition to BossRemote

---

README.md
requirements.txt
setup.py

Currently the intern install takes longer than it needs to due to having to install cloud-volume which has its own large set of prerequisites. 
I propose we change cloud-volume as an optional extra that can be installed if the user plans on using the cloud-volume remote. The install line would be as follows:
`pip install intern[cloudvolume]`

Set cloudvolume prerequisite as optional extra instead of always required.  

---

intern/service/boss/v1/volume.py

From downloading testing, `chunk_size` and the NumPy array construction significantly affected the overall speed of downloading cutouts. After some empirical testing I settled on some default values that will increase speed for typical download sizes. 
I also changed the array initialization to use `np.frombuffer` instead of `np.fromstring`. This is like some insane 62,000% increase in performance but in reality just cuts a couple milliseconds :)

Optimize chunk_size Parameter and Array Construction

---

intern/convenience/array.py
intern/convenience/uri.py

```python
from intern.convenience import volumes_from_neuroglancer
vols = volumes_from_neuroglancer("https://neuroglancer.bossdb.io/#! ... ")
```
This returns a dictionary where keys correspond to channel names in the neuroglancer page and arrays correspond to a volume of data around the center of the field of view from that URL. The optional parameter `radius_zyx` may be specified (`Tuple[int, int, int]`) to download a different shape of data.
```python
from intern.convenience import arrays_from_neuroglancer
datasets = arrays_from_neuroglancer("https://neuroglancer.bossdb.io/#! ... ")
```
This returns a dictionary where instead of volumes of data, `intern.array` objects are returned, which point to the channels from the neuroglancer URL.

Add neuroglancer convenience methods

---

.github/workflows/tests.yml
requirements.txt
setup.py

Tested install on python 3.6.14, 3.7.11, 3.8.11, 3.9.5, 3.9.6 for both general intern and intern['meshing'].

meshing now under extras_require

---

intern/resource/boss/resource.py

```python
>>> my_channel = BossRemote().get_channel( ... )
>>> my_channel.public
True
```

Add pass-through public property for Boss resources

---

.github/workflows/tests.yml

Python 3.6 [EOL'd on 23 Dec 2021](https://endoflife.date/python). There are a few things in 3.6 that have been keeping us from using the latest features of Python, so I'm making this PR to discuss removing it from our test suite and keeping the intern codebase up to the latest SotA!

Remove Python 3.6 from GitHub Actions tests

---

CHANGELOG.md
intern/convenience/array.py
intern/resource/boss/resource.py
intern/resource/boss/tests/test_collection.py
intern/service/boss/tests/test_baseversion.py

This adds a `Metadata` convenience class to navigate the BossDB project hierarchy:
```python
from intern.convenience import Metadata
m = Metadata("microns")
mp = m / "pinky100" # same as `Metadata("microns/pinky100")`
```
The `Metadata` class pretends to be a dict:
```python
>>> m.keys()
>>> m.items()
>>> m["my_key"]
>>> m["my_key"] = my_val
```
You can also explicitly ask for a dict version like so:
```python
m.to_dict()
```
Channels constructed with the `array` convenience class already have one of these as a `metadata` attribute:
```python
from intern import array
dataset = array("bossdb://...")
dataset.metadata.keys()
```

Add a metadata interface for all boss resources

---

CHANGELOG.md
intern/convenience/array.py
intern/version/__init__.py

#100 added warnings in the event that CloudVolume is not installed. However, [`warnings.simplefilter`](https://docs.python.org/3/library/warnings.html#warnings.simplefilter) expects the second argument to be a class (a category of warning), not a string.
https://github.com/jhuapl-boss/intern/blob/e1c0b4ab18b70cdd27e7c9a94cb0a0e864e979f0/intern/convenience/array.py#L51
This results in an error if the warning actually occurs:
```
TypeError: issubclass() arg 2 must be a class, a tuple of classes, or a union
```
I've replaced this with [`warnings.filterwarnings`](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings), which accepts a string for matching against warning messages.
(Discovered with @emmapbingham.)

Fix TypeError in non-cloudvolume case

---

intern/convenience/array.py

I noticed some duplicated code across `intern.convenience.array`'s `__getitem__` and `__setitem__` methods, which I condensed to a `normalize_key` private method. 
I'm separately interested in using this `_normalize_key` method for my work at DataJoint.
I ran `nose2 -c jenkins_files/unittest.cfg` both [before.log](https://github.com/jhuapl-boss/intern/files/10537188/tests_before.log) and [after.log](https://github.com/jhuapl-boss/intern/files/10537191/tests_after.log) my commit. Failures seem either pre-existing or related to my lack of `CloudVolume`.

Refactor slicing array to _normalize_key method and report voxel size relative to resolution

---

intern/service/boss/v1/volume.py
intern/service/dvid/volume.py

Collaborators were having issues following tutorial code because intern would fail to upload cutouts for arrays that weren't c-contiguous. This is hidden in the docs somewhere but I figured it would be a better user experience if we convert it during the cutout for them.

Adds c-order contiguous check

---

intern/remote/boss/tests/test_remote_get_cutout.py
intern/remote/boss/tests/test_remote_list.py
intern/remote/dvid/tests/test_remote_config.py
intern/service/boss/v1/tests/test_group.py
intern/service/boss/v1/tests/test_metadata.py
intern/service/boss/v1/tests/test_project.py
intern/service/boss/v1/tests/test_user.py
intern/service/boss/v1/tests/test_user_role.py
intern/service/boss/v1/tests/test_volume.py
intern/service/dvid/tests/test_project.py
intern/service/dvid/tests/test_versioning.py
intern/service/dvid/tests/test_volume.py
intern/service/mesh/tests/test_meshing.py
requirements.txt

Use `unittest.mock` (available in Python 3.3+) instead. See also: https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

Drop dependency on PyPI mock package

---

intern/service/cv/volume.py

Currently, pulling single index cutouts such as the one in https://github.com/aplbrain/bossdb_cookbook/blob/main/notebooks/Accessing-Lower-Resolution-Versions-Of-Data-From-BossDB.ipynb
error out because the cloud volume cutout is squeezed before being passed to the array convenience function, which tries to roll over the axis but because of the squeeze the array is now 2-dimensional. 
This fix addresses this issue by removing the squeeze and directly indexing the cutout to remove the channel dimension.

Fix single index cutouts for cloudvolume volume provider datasets

---

intern/convenience/array.py

Right now the remote has the wrong cloudpath when initialized via intern.array. Reproduce:
```
em = array('bossdb://microns/minnie65_8x8x40/em', resolution=mip)
print(em.volume_provider._cv.cloudvolume().resolution)
```
The remote isn't used for cutouts, but is useful for extracting metadata that is cloudvolume specific, such as `voxel_offset`.

Fix cv remote instantiation

---

intern/convenience/array.py

Previously, it was possible for the inference of the volume provider to fail if the user was creating all brand new resources. This resolves that error by falling back on boss DB volume providers based upon the protocol that the user specifies, since the `create_new` arg does not yet support cvdb.

fix: Support creating new resources with BossDB volume provider
